### PR TITLE
Bring back `partition_key`

### PR DESCRIPTION
**Pull request by dasch**
This should ensure backwards compatibility with Racecar v1.

### CODE REVIEW

**Comment by dasch** [comment]
Based on the work done in https://github.com/appsignal/rdkafka-ruby/pull/110.

**Comment by Adithya-copart** [comment]
I tried `rdkafka-0.7.0` in https://github.com/zendesk/racecar/pull/167 to see if the tests pass. The PR did not trigger a test suite run.

**Comment by dasch** [comment]
@Adithya-copart ran the tests on just the version bump, which passed. Looks like it's the use of `partition_key` which causes the problem.

**Comment by Adithya-copart** [comment]
https://github.com/zendesk/racecar/pull/169 should resolve the failures when merged into this branch.

**Pull request merged**
