### PR TITLE
Fix pause and resume bug

### PR DESCRIPTION
**Pull request by lairen**
Fixes https://github.com/zendesk/racecar/issues/335

### CODE REVIEW

**Comment by coopergillan** [comment]
@deepredsky - would someone be able to review this soon? It would be great to have this in the core gem. Thank you.

**Comment by deepredsky** [comment]
@lairen Thanks for you contribution! Changes in this PR looks good to me, I will test it locally sometime next with and merge to prepare for a release

**Comment by mensfeld** [comment]
@lairen this looks to Karafka client code: https://github.com/karafka/karafka/blob/38f7128ba9861df1aca1c75bdf7fbc85c94f35d0/lib/karafka/connection/client.rb#L58

```ruby
@paused_tpls = Hash.new { |h, k| h[k] = {} }
```

```ruby
@paused_tpls[topic][partition] = ...
```

```ruby
@paused_tpls[topic].delete(partition)
```

while I do not mind porting it is there a chance to point out the source of this contribution?

**Comment by lairen** [comment]
@mensfeld I set up the hash originally but I was inspired by the variable name so I can add a reference comment. how about this?

```
# inspired by https://github.com/karafka/karafka/blob/master/lib/karafka/connection/client.rb#L58
```

**Comment by mensfeld** [comment]
@lairen , sure that is fine.

Just please keep in mind for the future that Karafia is **NOT** MIT. WaterDrop is, karafka-rdkafka is as well but not Karafka. It is LGPL and Commercial (when talking about Pro enhancements). This means that if you take concepts or ideas out of it and copy-paste them to a different location/repository, it must comply with LGPL license that states, amongst others, that:

> You may modify your copy or copies of the Library or any portion of it, thus forming a work based on the Library, and copy and distribute such modifications or work under the terms of Section 1 above, provided that you also meet all of these conditions:
 (...)
    c) You must cause the whole of the work to be licensed at no charge to all third parties under the terms of this License. 
    
Since racecar is MIT, it is not compatible with LGPL license under which karafka is licensed. 

While this contribution is okay because it is a minor bug fix, and I'm happy with the notice, I do not appreciate copying more significant concepts or solutions from karafka to other libraries without fulfilling the LGPL requirements. I explicitly chose LGPL because it strikes a balance between freedom of open-source and protection of my work, and I would highly appreciate it if this choice was respected.

As stated, my solutions are not closed-sourced and OSSed for people to learn, understand, change, and bugfix (if they want) but are also released under specific licenses on purpose.

**Comment by lairen** [comment]
@mensfeld Both libraries had already implemented pausing and resuming logic on the topic and partition using rdkafka's `TopicPartitionList`. The least invasive approach to fix the bug that I was seeing was to keep track of the paused partitions that may have been revoked during the consumer rebalance or lost entirely, which I noticed with a running racecar consumer.  The idea of tracking these partitions did not come from looking at Karafka's code. It came from looking at logs,  observing a running Racecar consumer, and looking at the solutions proposed in the original issue https://github.com/zendesk/racecar/issues/335 .  If the licensing concern here is the hash itself, this  `paused_tpls` hash has a different structure and deletion logic from the one in Karafka's code. 

As long as the racecar maintainers don't have any issues with the comment or the licensing concerns that you brought up, I will add the "inspired by" comment to this PR for the variable name.

**Comment by mensfeld** [comment]
@lairen thank you for your kind answer :pray:

My remark was a general one. It's a minor piece of code, and as I said, I am happy with an indication if it was inspired or even without if that would block racecar maintainers from merging it as I understand the severity of this bug.

To be clear on my intent with this PR: **no** intention to impose any license changes with this code, and I am happy for it to be MIT as it is (as I am a strong MIT supporter as well).

My point was general, as I saw some other PRs referencing my solutions with the indication of "there's a solution / proposed approach." hence, I wanted to clarify how I see derivatives coming from Karafka.

We operate in the same space, and I appreciate all the work that everyone is doing to move Kafka for Ruby forward :heart:

**Comment by lairen** [comment]
@mensfeld I didn't have the background on previous PRs with your solutions in them, so thanks for that clarification! There are surprisingly few Kafka Ruby libraries, so I also appreciate the Racecar community and your contributions with Karafka/ Waterdrop  ❤️

**Review by deepredsky — APPROVED** [review]

**Comment by dasch** [comment]
Thanks!

I consider the licensing issue resolved with @mensfeld's comments: this does not constitute a violation of licenses (but please don't copy paste more code from other repos :))

**Comment by mensfeld** [comment]
> consider the licensing issue resolved with @mensfeld's comments

Yes.

> but please don't copy paste more code from other repos

Or do it according to the source license ;)

**Pull request merged**
