### PR TITLE
Resolve Rails 7.1 logger incompatibility

### PR DESCRIPTION
**Pull request by zubin**
Resolves https://github.com/zendesk/racecar/issues/356

There don't appear to be any tests which cover this but I've verified that it works locally.

### CODE REVIEW

**Comment by gkosmo** [comment]
Out of curiosity, why was this PR closed ? This fix looks good to me ( it's the same strategy as used on sidekiq )

**Comment by deepredsky** [comment]
The patch here should work, @zubin I m happy to merge this patch unless you found some issue with this change

**Comment by zubin** [comment]
> The patch here should work, @zubin I m happy to merge this patch unless you found some issue with this change

No issues, it's been working fine. 👍

**Comment by dorianmarie** [comment]
@deepredsky Could you release a new version please?

**Comment by dorianmarie** [comment]
Oh I see there is 2.10.0.beta2, why not a non-beta version?

**Comment by deepredsky** [comment]
> Oh I see there is 2.10.0.beta2, why not a non-beta version?

2.10.0 is released now

**Pull request merged**
