### PR TITLE
Add support for cooperative-sticky assignment strategy

### PR DESCRIPTION
**Pull request by bestie**
Features:
- Support for cooperative-sticky assignment strategy
- Consumer class partition assign and revoke callbacks

Tests:
- Refactor to share a common consumer

### CODE REVIEW

**Comment by deepredsky** [comment]
The changes in this PR looks good. But there is reported issue about cooperative sticky failing with a  crash on close prior to first rebalance.

Deep dive and some suggestion fix here: https://github.com/confluentinc/librdkafka/issues/4312

**Comment by mensfeld** [comment]
> Deep dive and some suggestion fix here

Just a reminder that my bypass code is released under **LGPL** and not MIT (talking about karafka, not rdkafka-ruby or waterdrop).

**Comment by mensfeld** [comment]
ah and this is a bypass. 2.2.1 librdkafka should be the one to include the correct fix and then it should be "passed" on to rdkafka-ruby via a dep bump.

**Review by deepredsky — APPROVED** [review]

**Comment by mensfeld** [comment]
@deepredsky just a heads up: 2.3.0 has been released. I should ship 0.14.0 rdkafka-ruby in the upcoming weeks once I test it fully. All should be good then.

**Pull request merged**
